spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  sql:
    init:
      platform: postgres

project:
  poster: /posters

base:
  url: "http://localhost:8080"
