package com.example.springmovie.service;

// Import necessary packages for movie operations, file handling, and data management
import com.example.springmovie.dto.MovieDto;
import com.example.springmovie.entities.Movie;
import com.example.springmovie.repositories.MovieRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

@Service // Marks the class as a service, making it eligible for Spring's dependency injection
public class MovieServiceImpl implements MovieService {

    private final MovieRepository movieRepository;
    private final FileService fileService;

    // Injects values from the application properties (like poster storage path and base URL)
    @Value("${project.poster}")
    private String path;

    @Value("${base.url}")
    private String baseUrl;

    // Constructor-based dependency injection
    public MovieServiceImpl(MovieRepository movieRepository, FileService fileService) {
        this.movieRepository = movieRepository;
        this.fileService = fileService;
    }

    @Override
    public MovieDto addMovie(MovieDto movieDto, MultipartFile file) throws IOException {
        // 1. Check if file with the same name already exists
        Path filePath = Paths.get(path, file.getOriginalFilename());
        if (Files.exists(filePath)) {
            throw new IOException("File already exists! Please enter another file name!");
        }

        // 2. Upload the file and get the name of the uploaded file
        String uploadedFileName = fileService.uploadFile(path, file);

        // 3. Set the 'poster' field in the movieDto with the uploaded file's name
        movieDto.setPoster(uploadedFileName);

        // 4. Convert the MovieDto to a Movie entity object
        Movie movie = new Movie(
                null, // Set movie ID as null (auto-generated by the database)
                movieDto.getTitle(),
                movieDto.getGenre(),
                movieDto.getDirector(),
                movieDto.getReleaseDate(),
                movieDto.getPoster(),
                movieDto.getMovieCast()
        );

        // 5. Save the movie entity to the database
        Movie savedMovie = movieRepository.save(movie);

        // 6. Generate the URL for the uploaded poster
        String posterUrl = baseUrl + "/file/" + uploadedFileName;

        // 7. Return the MovieDto with the new poster URL
        return new MovieDto(
                savedMovie.getMovieId(),
                savedMovie.getTitle(),
                savedMovie.getGenre(),
                savedMovie.getDirector(),
                savedMovie.getReleaseDate(),
                savedMovie.getPoster(),
                posterUrl,
                savedMovie.getMovieCast()
        );
    }

    @Override
    public MovieDto getMovie(Integer movieId) {
        // 1. Retrieve the movie entity by ID from the database
        Movie movie = movieRepository.findById(Long.valueOf(movieId))
                .orElseThrow(() -> new IndexOutOfBoundsException("Movie not found with id = " + movieId));

        // 2. Generate the poster URL using the base URL and movie poster name
        String posterUrl = baseUrl + "/file/" + movie.getPoster();

        // 3. Return the movie as a MovieDto
        return new MovieDto(
                movie.getMovieId(),
                movie.getTitle(),
                movie.getGenre(),
                movie.getDirector(),
                movie.getReleaseDate(),
                movie.getPoster(),
                posterUrl,
                movie.getMovieCast()
        );
    }

    @Override
    public List<MovieDto> getAllMovies() {
        // 1. Fetch all movies from the database
        List<Movie> movies = movieRepository.findAll();

        // 2. Map each movie entity to a MovieDto object and return the list of MovieDto objects
        return movies.stream()
                .map(movie -> {
                    String posterUrl = baseUrl + "/file/" + movie.getPoster();
                    return new MovieDto(
                            movie.getMovieId(),
                            movie.getTitle(),
                            movie.getGenre(),
                            movie.getDirector(),
                            movie.getReleaseDate(),
                            movie.getPoster(),
                            posterUrl,
                            movie.getMovieCast()
                    );
                })
                .collect(Collectors.toList());
    }

    @Override
    public MovieDto updateMovie(MovieDto movieDto, Integer movieId, MultipartFile file) throws IOException {
        // 1. Retrieve the existing movie from the database
        Movie movieDB = movieRepository.findById(Long.valueOf(movieDto.getMovieId()))
                .orElseThrow(() -> new IOException("Movie not found with id = " + movieId));

        // 2. Initialize the existing file name (poster)
        String fileName = movieDB.getPoster();

        // 3. If a new file is provided, delete the old file and upload the new one
        if (file != null) {
            Files.deleteIfExists(Paths.get(path + File.separator + fileName)); // Delete old file
            fileName = fileService.uploadFile(path, file); // Upload new file
        }

        // 4. Set the poster field in the movieDto to the (new or old) file name
        movieDto.setPoster(fileName);

        // 5. Update the movie entity with the new values from the DTO
        Movie movie = new Movie(
                movieDB.getMovieId(),
                movieDto.getTitle(),
                movieDto.getGenre(),
                movieDto.getDirector(),
                movieDto.getReleaseDate(),
                movieDto.getPoster(),
                movieDto.getMovieCast()
        );

        // 6. Save the updated movie entity to the database
        Movie updatedMovie = movieRepository.save(movie);

        // 7. Generate the new poster URL
        String posterUrl = baseUrl + "/file/" + updatedMovie.getPoster();

        // 8. Return the updated MovieDto with the new poster URL
        return new MovieDto(
                updatedMovie.getMovieId(),
                updatedMovie.getTitle(),
                updatedMovie.getGenre(),
                updatedMovie.getDirector(),
                updatedMovie.getReleaseDate(),
                updatedMovie.getPoster(),
                posterUrl,
                updatedMovie.getMovieCast()
        );
    }

    @Override
    public String deleteMovie(Integer movieId) throws IOException {
        // 1. Retrieve the movie entity by ID
        Movie mv = movieRepository.findById(Long.valueOf(movieId))
                .orElseThrow(() -> new IOException("Movie not found with id = " + movieId));

        // 2. Delete the movie poster file from the server
        Files.deleteIfExists(Paths.get(path + File.separator + mv.getPoster()));

        // 3. Delete the movie entity from the database
        movieRepository.delete(mv);

        // 4. Return a confirmation message
        return "Movie object deleted with id = " + mv.getMovieId();
    }
}
